// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtxwfrlcdfqtlhviinub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0eHdmcmxjZGZxdGxodmlpbnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzA1MzgsImV4cCI6MjA2MDY0NjUzOH0.NitRHHQ6GECtgUCG3cDTTK9xq29kE44aTGAgubYCpo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);